# Generated by Django 5.2.16 on 2026-07-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_reaction_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="disappearing_duration",
            field=models.IntegerField(
                choices=[
                    (0, "Off"),
                    (30, "30 seconds"),
                    (300, "5 minutes"),
                    (3600, "1 hour"),
                    (86400, "1 day"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
